#include "canvaswidget.h"
#include "fluxdocument.h"
#include "fluxcanvasengine.h"
#include "fluxselection.h"
#include "fluxbrush.h"
#include <QFileInfo>
#include <QInputDialog>
#include <QLineEdit>
#include <QMouseEvent>
#include <QPainter>
#include <QPainterPath>
#include <QPointingDevice>
#include <QPolygonF>
#include <QResizeEvent>
#include <QSet>
#include <QTabletEvent>
#include <QWheelEvent>
#include <algorithm>
#include <cmath>

namespace { constexpr qreal Pi=3.1415926535897932384626433832795; }

FluxCanvas::FluxCanvas(QWidget* parent):QOpenGLWidget(parent){setFocusPolicy(Qt::StrongFocus);setMouseTracking(true);setAttribute(Qt::WA_OpaquePaintEvent);m_engine=new FluxCanvasEngine;m_selection=new FluxSelectionEngine;m_transform=new FluxTransform;m_brush=new BrushEngine;}
void FluxCanvas::setDocument(FluxDocument* document){m_document=document;m_engine->setDocument(document);m_undo.clear();m_redo.clear();fitCanvas();update();}
void FluxCanvas::setBrushSize(int px){m_brushSize=std::clamp(px,1,1000);auto p=m_brush->preset();p.size=m_brushSize;m_brush->setPreset(p);emit brushSizeChanged(m_brushSize);update();}
void FluxCanvas::setBrushColor(const QColor& color){if(color.isValid()){m_brushColor=color;m_brush->setColor(color);}update();}
void FluxCanvas::setTool(const QString& tool){m_tool=tool;update();}
void FluxCanvas::fitCanvas(){if(!m_document)return;m_engine->fitToViewport(size());emit zoomChanged(m_engine->zoom());update();}
double FluxCanvas::zoom()const{return m_engine?m_engine->zoom():1.0;}
void FluxCanvas::setMirrorHorizontal(bool enabled){m_engine->setMirror(enabled,m_engine->mirrorVertical());update();}
void FluxCanvas::setMirrorVertical(bool enabled){m_engine->setMirror(m_engine->mirrorHorizontal(),enabled);update();}
void FluxCanvas::setCanvasRotation(qreal degrees){m_engine->setRotation(degrees);update();}
void FluxCanvas::setPixelPerfect(bool enabled){m_engine->setPixelPerfect(enabled);update();}
void FluxCanvas::setStabilization(qreal amount){m_stabilization=qBound(0.0,amount,1.0);auto p=m_brush->preset();p.stabilization=m_stabilization;m_brush->setPreset(p);}
void FluxCanvas::setSymmetry(bool horizontal,bool vertical){m_symmetryH=horizontal;m_symmetryV=vertical;update();}
bool FluxCanvas::loadReference(const QString& path){QImage img(path);if(img.isNull())return false;m_referenceImage=img;m_referencePosition={0,0};emit referenceChanged();update();return true;}
void FluxCanvas::clearReference(){m_referenceImage=QImage();emit referenceChanged();update();}
void FluxCanvas::setPerspectiveGuide(bool enabled){m_perspective=enabled;update();}
void FluxCanvas::setGridEnabled(bool enabled){m_grid=enabled;update();}
void FluxCanvas::setRulersEnabled(bool enabled){m_rulers=enabled;update();}
QPointF FluxCanvas::widgetToCanvas(const QPointF&p)const{return m_engine?m_engine->widgetToCanvas(p,size()):QPointF();}
QPointF FluxCanvas::canvasToWidget(const QPointF&p)const{return m_engine?m_engine->canvasToWidget(p,size()):QPointF();}
void FluxCanvas::pushUndoState(){if(!m_document)return;m_undo.push_back(m_document->activeImage().copy());if(m_undo.size()>60)m_undo.remove(0);m_redo.clear();}
void FluxCanvas::undo(){if(!m_document||m_undo.isEmpty())return;m_redo.push_back(m_document->activeImage().copy());m_document->activeImage()=m_undo.takeLast();m_engine->invalidate();emit documentChanged();update();}
void FluxCanvas::redo(){if(!m_document||m_redo.isEmpty())return;m_undo.push_back(m_document->activeImage().copy());m_document->activeImage()=m_redo.takeLast();m_engine->invalidate();emit documentChanged();update();}
bool FluxCanvas::isShapeTool()const{return m_tool=="Line"||m_tool=="Rectangle"||m_tool=="Ellipse"||m_tool=="Polygon"||m_tool=="Star"||m_tool=="Bezier"||m_tool=="Gradient";}
void FluxCanvas::drawShape(const QPointF&from,const QPointF&to){if(!m_document||m_document->activeLayer().locked)return;QPainter p(&m_document->activeImage());p.setRenderHint(QPainter::Antialiasing,!m_engine->pixelPerfect());QPen pen(m_brushColor,std::max(1,m_brushSize),Qt::SolidLine,Qt::RoundCap,Qt::RoundJoin);p.setPen(pen);p.setBrush(Qt::NoBrush);const QRectF r=QRectF(from,to).normalized();if(m_tool=="Line")p.drawLine(from,to);else if(m_tool=="Rectangle")p.drawRect(r);else if(m_tool=="Ellipse")p.drawEllipse(r);else if(m_tool=="Polygon"||m_tool=="Star"){const QPointF c=r.center();const qreal rx=r.width()/2.,ry=r.height()/2.;const int n=m_tool=="Star"?10:6;QPolygonF poly;for(int i=0;i<n;++i){const qreal a=-Pi/2+i*(2*Pi/n);const qreal rr=(m_tool=="Star"&&i%2)?0.48:1.;poly<<QPointF(c.x()+std::cos(a)*rx*rr,c.y()+std::sin(a)*ry*rr);}p.drawPolygon(poly);}else if(m_tool=="Bezier"){QPainterPath path(from);const QPointF d=to-from;const QPointF n(-d.y()*.35,d.x()*.35);path.cubicTo(from+d*.33+n,from+d*.66-n,to);p.drawPath(path);}else if(m_tool=="Gradient"){QLinearGradient g(from,to);g.setColorAt(0,m_brushColor);QColor end=m_brushColor;end.setAlpha(0);g.setColorAt(1,end);p.setPen(Qt::NoPen);p.setBrush(g);p.drawRect(r);}p.end();m_engine->invalidate();emit documentChanged();}
void FluxCanvas::bucketFill(const QPointF&point){if(!m_document||m_document->activeLayer().locked)return;QImage&img=m_document->activeImage();const QPoint seed(qRound(point.x()),qRound(point.y()));if(!img.rect().contains(seed))return;const QColor target=img.pixelColor(seed);if(target==m_brushColor)return;pushUndoState();QVector<QPoint> stack{seed};QSet<quint64>seen;const int w=img.width(),h=img.height();auto key=[w](const QPoint&p){return quint64(p.y())*quint64(w)+quint64(p.x());};while(!stack.isEmpty()){const QPoint p=stack.takeLast();const auto k=key(p);if(seen.contains(k))continue;seen.insert(k);if(img.pixelColor(p)!=target)continue;img.setPixelColor(p,m_brushColor);if(p.x()>0)stack.push_back({p.x()-1,p.y()});if(p.x()+1<w)stack.push_back({p.x()+1,p.y()});if(p.y()>0)stack.push_back({p.x(),p.y()-1});if(p.y()+1<h)stack.push_back({p.x(),p.y()+1});}m_engine->invalidate();emit documentChanged();}
void FluxCanvas::pickColor(const QPointF&point){if(!m_document)return;const QPoint p(qRound(point.x()),qRound(point.y()));if(!m_document->activeImage().rect().contains(p))return;setBrushColor(m_document->activeImage().pixelColor(p));emit cursorInfoChanged(QStringLiteral("Sampled %1").arg(m_brushColor.name(QColor::HexArgb)));}
void FluxCanvas::insertText(const QPointF&point){if(!m_document||m_document->activeLayer().locked)return;bool ok=false;const QString value=QInputDialog::getText(this,"Flux Text","Text:",QLineEdit::Normal,QString(),&ok);if(!ok||value.isEmpty())return;pushUndoState();QPainter p(&m_document->activeImage());p.setPen(m_brushColor);p.setFont(QFont("Segoe UI",std::max(8,m_brushSize*2),QFont::Normal));p.drawText(point,value);p.end();m_engine->invalidate();emit documentChanged();}
void FluxCanvas::handlePointer(const QPointF&pos,qreal pressure,qreal tiltX,qreal tiltY,qreal rotation){if(!m_document||m_document->activeLayer().locked)return;BrushInput input;input.position=widgetToCanvas(pos);input.pressure=pressure;input.tiltX=tiltX;input.tiltY=tiltY;input.rotation=rotation;input.velocity=QLineF(m_lastPoint,input.position).length();auto preset=m_brush->preset();if(m_tool=="Pencil"){preset.opacity=.78;preset.spacing=.10;}else if(m_tool=="Ink"){preset.opacity=1.;preset.spacing=.14;}else if(m_tool=="Airbrush"){preset.opacity=.24;preset.spacing=.12;preset.jitter=.03;}else if(m_tool=="Marker"){preset.opacity=.65;preset.spacing=.08;}else if(m_tool=="Eraser"){preset.color=Qt::transparent;preset.opacity=1.;}else{preset.color=m_brushColor;preset.opacity=1.;}m_brush->setPreset(preset);drawSymmetricStroke(input);m_engine->invalidate();emit documentChanged();m_lastPoint=input.position;m_cursor=pos;}
void FluxCanvas::drawSymmetricStroke(const BrushInput&input){m_brush->addPoint(m_document->activeImage(),input);const qreal cx=m_document->width()/2.0,cy=m_document->height()/2.0;auto mirrorPoint=[&](QPointF p,bool x,bool y){if(x)p.setX(2*cx-p.x());if(y)p.setY(2*cy-p.y());return p;};for(bool x:{false,m_symmetryH})for(bool y:{false,m_symmetryV})if(x||y){BrushInput copy=input;copy.position=mirrorPoint(input.position,x,y);m_brush->addPoint(m_document->activeImage(),copy);}}
void FluxCanvas::beginSelection(const QPointF&point){m_selecting=true;m_selectionStart=point;m_lasso.clear();m_lasso.push_back(point);}
void FluxCanvas::updateSelection(const QPointF&point){if(!m_selecting)return;m_cursor=point;if(m_tool=="Lasso Select")m_lasso.push_back(point);update();}
void FluxCanvas::finishSelection(){if(!m_selecting||!m_document)return;m_selecting=false;if(m_tool=="Rectangle Select")m_selection->rectangle(QRectF(widgetToCanvas(m_selectionStart),widgetToCanvas(m_cursor)).normalized().toRect());else if(m_lasso.size()>=3){QPolygon poly;for(const auto&p:m_lasso)poly<<widgetToCanvas(p).toPoint();m_selection->lasso(poly);}emit selectionChanged();update();}
void FluxCanvas::clearSelection(){m_selection->clear();emit selectionChanged();update();}
void FluxCanvas::selectAll(){if(!m_document)return;m_selection->rectangle(QRect(0,0,m_document->width(),m_document->height()));emit selectionChanged();update();}
void FluxCanvas::applySelectionTransform(){if(!m_document||m_selection->isEmpty())return;pushUndoState();const QRect b=m_selection->bounds();QImage part=m_document->activeImage().copy(b);QPainter p(&m_document->activeImage());p.setCompositionMode(QPainter::CompositionMode_Clear);p.drawRect(b);p.setCompositionMode(QPainter::CompositionMode_SourceOver);p.drawImage(b.topLeft(),part.transformed(m_transform->matrix(),Qt::SmoothTransformation));p.end();m_engine->invalidate();emit documentChanged();update();}
void FluxCanvas::drawOnion(QPainter&p,const QRectF&target,int frame,qreal opacity){if(!m_document||frame<0||frame>=m_document->frameCount())return;for(const auto&layer:m_document->layers()){if(!layer.visible||layer.frames.size()<m_document->frameCount())continue;const QImage img=layer.frames[frame];if(img.isNull())continue;p.save();p.setOpacity(opacity*layer.opacity);p.drawImage(target,img);p.restore();}}
void FluxCanvas::drawReference(QPainter&p,const QRectF&canvasRect){if(m_referenceImage.isNull())return;p.save();p.setOpacity(.32);const qreal scale=qMin(canvasRect.width()/m_referenceImage.width(),canvasRect.height()/m_referenceImage.height());QRectF dst(canvasRect.topLeft(),QSizeF(m_referenceImage.width()*scale,m_referenceImage.height()*scale));p.drawImage(dst,m_referenceImage);p.restore();}
void FluxCanvas::drawSelectionOverlay(QPainter&p){if(!m_selection||m_selection->isEmpty())return;const QRectF r=QRectF(canvasToWidget(m_selection->bounds().topLeft()),canvasToWidget(m_selection->bounds().bottomRight())).normalized();p.save();p.setPen(QPen(QColor("#ffffff"),1,Qt::DashLine));p.setBrush(Qt::NoBrush);p.drawRect(r);const qreal hs=7;for(const auto&q:{r.topLeft(),r.topRight(),r.bottomRight(),r.bottomLeft(),QPointF(r.center().x(),r.top()),QPointF(r.right(),r.center().y()),QPointF(r.center().x(),r.bottom()),QPointF(r.left(),r.center().y())}){p.setBrush(QColor("#111318"));p.drawRect(QRectF(q-QPointF(hs/2,hs/2),QSizeF(hs,hs)));}p.restore();}
void FluxCanvas::drawGuides(QPainter&p){if(!m_document)return;p.save();if(m_grid){p.setPen(QPen(QColor(150,160,180,55),1,Qt::DotLine));for(int x=0;x<=m_document->width();x+=100)p.drawLine(canvasToWidget({double(x),0}),canvasToWidget({double(x),double(m_document->height())}));for(int y=0;y<=m_document->height();y+=100)p.drawLine(canvasToWidget({0,double(y)}),canvasToWidget({double(m_document->width()),double(y)}));}if(m_rulers){p.setPen(QPen(QColor(170,176,188,90),1));for(int x=0;x<m_document->width();x+=500)p.drawText(canvasToWidget({double(x),18})+QPointF(3,0),QString::number(x));for(int y=0;y<m_document->height();y+=500)p.drawText(canvasToWidget({18,double(y)})+QPointF(3,0),QString::number(y));}if(m_perspective){const QPointF vp(width()/2.0,height()/2.0-qMin(120.0,double(height())/4.0));p.setPen(QPen(QColor(120,190,255,90),1,Qt::DashLine));for(int i=0;i<9;++i){const qreal x=i*(width()/8.0);p.drawLine(vp,QPointF(x,height()));}p.drawLine(QPointF(0,height()*.72),QPointF(width(),height()*.72));}p.restore();}
void FluxCanvas::paintEvent(QPaintEvent*){QPainter p(this);p.setRenderHint(QPainter::Antialiasing,!m_engine->pixelPerfect());p.fillRect(rect(),QColor("#0d0f13"));if(!m_document)return;const QRectF r=QRectF(canvasToWidget({0,0}),canvasToWidget({double(m_document->width()),double(m_document->height())})).normalized();p.save();p.setClipRect(r);const int cell=18;for(int y=int(r.top());y<r.bottom();y+=cell)for(int x=int(r.left());x<r.right();x+=cell)p.fillRect(x,y,cell,cell,((x/cell+y/cell)&1)?QColor("#e0e2e5"):QColor("#f1f2f4"));drawReference(p,r);if(m_onionSkin&&m_document->frame()>0)drawOnion(p,r,m_document->frame()-1,.20);if(m_onionSkin&&m_document->frame()+1<m_document->frameCount())drawOnion(p,r,m_document->frame()+1,.13);m_engine->draw(p,size());p.restore();p.setPen(QPen(QColor("#4a505c"),1));p.drawRect(r);drawGuides(p);drawSelectionOverlay(p);if(m_drawing&&isShapeTool()){p.save();p.setPen(QPen(QColor("#b7c4d6"),1,Qt::DashLine));p.setBrush(Qt::NoBrush);const QRectF wr=QRectF(canvasToWidget(m_toolStart),m_cursor).normalized();if(m_tool=="Line")p.drawLine(canvasToWidget(m_toolStart),m_cursor);else if(m_tool=="Rectangle")p.drawRect(wr);else if(m_tool=="Ellipse")p.drawEllipse(wr);else p.drawRect(wr);p.restore();}p.setPen(QColor("#9ba2ae"));p.setFont(QFont("Segoe UI",10));p.drawText(16,25,QString("%1  •  %2%  •  %3 × %4  •  Frame %5").arg(m_tool).arg(int(zoom()*100)).arg(m_document->width()).arg(m_document->height()).arg(m_document->frame()+1));if(m_selecting&&m_tool=="Lasso Select"&&m_lasso.size()>1){p.setPen(QPen(QColor("#aeb5c0"),1,Qt::DashLine));for(int i=1;i<m_lasso.size();++i)p.drawLine(m_lasso[i-1],m_lasso[i]);}if(m_selecting&&m_tool=="Rectangle Select")p.drawRect(QRectF(m_selectionStart,m_cursor).normalized());QString tabletHint=QStringLiteral("Tablet ready • Pressure %1 • Tilt %2°/%3° • Rotation %4°").arg(m_pressure,0,'f',2).arg(m_tiltX,0,'f',0).arg(m_tiltY,0,'f',0).arg(m_rotationInput,0,'f',0);p.drawText(QRectF(12,height()-24,width()-24,20),Qt::AlignRight|Qt::AlignVCenter,tabletHint);p.drawText(QRectF(0,0,width(),height()),Qt::AlignBottom|Qt::AlignHCenter,"Pressure • Tilt • Rotation  |  Stylus buttons: barrel-right = Flux Wheel, barrel-middle = Pan, eraser tip = Eraser  |  Ctrl+wheel zoom  |  Shift+wheel pan");}
void FluxCanvas::mousePressEvent(QMouseEvent*e){if(e->button()==Qt::RightButton){emit wheelRequested(e->globalPosition().toPoint());return;}if(e->button()!=Qt::LeftButton||!m_document)return;const QPointF canvasPoint=widgetToCanvas(e->position());if(m_tool=="Rectangle Select"||m_tool=="Lasso Select"){beginSelection(e->position());return;}if(m_tool=="Fill"){bucketFill(canvasPoint);return;}if(m_tool=="Color Picker"){pickColor(canvasPoint);return;}if(m_tool=="Text"){insertText(canvasPoint);return;}if(m_tool=="Transform"){if(!m_selection->isEmpty()){m_transform->reset(m_selection->bounds());m_transformStart=e->position();m_transforming=true;}return;}if(isShapeTool()){m_drawing=true;m_toolStart=canvasPoint;m_cursor=e->position();pushUndoState();update();return;}m_drawing=true;m_pressure=1.;m_tiltX=m_tiltY=m_rotationInput=0;m_lastPoint=canvasPoint;pushUndoState();m_brush->beginStroke({m_lastPoint,1.,0,0,0,0});handlePointer(e->position(),1.,0,0,0);update();}
void FluxCanvas::mouseMoveEvent(QMouseEvent*e){m_cursor=e->position();if(m_selecting){updateSelection(e->position());return;}if(m_transforming){const QPointF d=e->position()-m_transformStart;m_transform->reset(m_selection->bounds());m_transform->translate({d.x()/zoom(),d.y()/zoom()});update();return;}if(!m_drawing)return;if(isShapeTool()){update();return;}handlePointer(e->position(),m_pressure,m_tiltX,m_tiltY,m_rotationInput);emit cursorInfoChanged(QString("X %1  Y %2  Pressure %3  Tilt %4,%5").arg(int(m_lastPoint.x())).arg(int(m_lastPoint.y())).arg(m_pressure,0,'f',2).arg(m_tiltX,0,'f',1).arg(m_tiltY,0,'f',1));update();}
void FluxCanvas::mouseReleaseEvent(QMouseEvent*e){if(e->button()!=Qt::LeftButton)return;if(m_selecting){finishSelection();return;}if(m_transforming){m_transforming=false;applySelectionTransform();return;}if(m_drawing){if(isShapeTool())drawShape(m_toolStart,widgetToCanvas(e->position()));else{handlePointer(e->position(),m_pressure,m_tiltX,m_tiltY,m_rotationInput);m_brush->endStroke();}m_drawing=false;emit documentChanged();update();}}
QString FluxCanvas::tabletPointerName(QTabletEvent*e)const{return e->pointerType()==QPointingDevice::PointerType::Eraser?QStringLiteral("Eraser"):QStringLiteral("Pen");}
bool FluxCanvas::tabletUsesPan(QTabletEvent*e)const{return (e->buttons()&Qt::MiddleButton)!=0;}
bool FluxCanvas::tabletUsesWheel(QTabletEvent*e)const{return (e->buttons()&Qt::RightButton)!=0;}
void FluxCanvas::beginTabletStroke(QTabletEvent*e){if(!m_document)return;m_tabletEraserActive=(e->pointerType()==QPointingDevice::PointerType::Eraser);m_preTabletTool=m_tool;if(m_tabletEraserActive)m_tool=QStringLiteral("Eraser");m_tabletPanActive=tabletUsesPan(e);m_tabletWheelActive=tabletUsesWheel(e);m_pressure=e->pressure();m_tiltX=e->xTilt();m_tiltY=e->yTilt();m_rotationInput=e->rotation();m_lastPoint=widgetToCanvas(e->position());m_cursor=e->position();if(m_tool=="Rectangle Select"||m_tool=="Lasso Select"){beginSelection(e->position());return;}if(m_tabletPanActive||m_tabletWheelActive)return;if(m_document->activeLayer().locked)return;pushUndoState();m_drawing=true;m_brush->beginStroke({m_lastPoint,m_pressure,m_tiltX,m_tiltY,m_rotationInput,0});handlePointer(e->position(),m_pressure,m_tiltX,m_tiltY,m_rotationInput);emit strokeStarted();}
void FluxCanvas::updateTabletStroke(QTabletEvent*e){m_pressure=e->pressure();m_tiltX=e->xTilt();m_tiltY=e->yTilt();m_rotationInput=e->rotation();const QPointF now=e->position();const QPointF delta=now-m_cursor;m_tabletPanActive=tabletUsesPan(e);m_tabletWheelActive=tabletUsesWheel(e);if(m_selecting){updateSelection(now);return;}if(m_tabletPanActive){m_engine->panBy(delta);m_cursor=now;update();return;}if(m_tabletWheelActive){if(!qFuzzyIsNull(delta.y())){const qreal next=qBound(.05,m_engine->zoom()*(delta.y()<0?1.01:.99),32.0);m_engine->setZoom(next);emit zoomChanged(next);}m_cursor=now;update();return;}m_cursor=now;if(!m_drawing)return;if(isShapeTool()){update();return;}handlePointer(now,m_pressure,m_tiltX,m_tiltY,m_rotationInput);emit cursorInfoChanged(QString("Tablet • %1 • Pressure %2 • Tilt %3,%4 • Rotation %5").arg(tabletPointerName(e)).arg(m_pressure,0,'f',2).arg(m_tiltX,0,'f',1).arg(m_tiltY,0,'f',1).arg(m_rotationInput,0,'f',1));update();}
void FluxCanvas::finishTabletStroke(QTabletEvent*e){m_pressure=e->pressure();m_tiltX=e->xTilt();m_tiltY=e->yTilt();m_rotationInput=e->rotation();if(m_selecting){finishSelection();}else if(m_drawing){if(isShapeTool())drawShape(m_toolStart,widgetToCanvas(e->position()));else{handlePointer(e->position(),m_pressure,m_tiltX,m_tiltY,m_rotationInput);m_brush->endStroke();}m_drawing=false;emit documentChanged();}m_tabletPanActive=false;m_tabletWheelActive=false;if(m_tabletEraserActive){m_tool=m_preTabletTool;m_preTabletTool.clear();m_tabletEraserActive=false;}emit tabletInfoChanged(QStringLiteral("Stylus: %1 • pressure %2 • tilt %3°/%4° • rotation %5°").arg(tabletPointerName(e)).arg(m_pressure,0,'f',0).arg(m_tiltX,0,'f',0).arg(m_tiltY,0,'f',0).arg(m_rotationInput,0,'f',0));update();}
void FluxCanvas::tabletEvent(QTabletEvent*e){switch(e->type()){case QEvent::TabletPress:beginTabletStroke(e);break;case QEvent::TabletMove:updateTabletStroke(e);break;case QEvent::TabletRelease:finishTabletStroke(e);break;default:break;}e->accept();}
void FluxCanvas::wheelEvent(QWheelEvent*e){if(e->modifiers()&Qt::ControlModifier){const qreal next=qBound(.05,m_engine->zoom()*(e->angleDelta().y()>0?1.1:.9),32.0);m_engine->setZoom(next);emit zoomChanged(next);update();e->accept();return;}if(e->modifiers()&Qt::ShiftModifier){m_engine->panBy({double(e->angleDelta().x()),double(e->angleDelta().y())});update();e->accept();return;}QOpenGLWidget::wheelEvent(e);}
void FluxCanvas::resizeEvent(QResizeEvent*e){QOpenGLWidget::resizeEvent(e);update();}
