#include "fluxmedia.h"
#include <QProcess>
#include <QRegularExpression>
#include <QtEndian>
#include <cmath>

bool FluxMediaEngine::runFfmpeg(const QStringList&args,QByteArray*stdoutData,QByteArray*stderrData,QString*error){QProcess p;p.setProgram(QStringLiteral("ffmpeg"));p.setArguments(args);p.start();if(!p.waitForStarted(3000)){if(error)*error="FFmpeg was not found. Install FFmpeg or add it to PATH.";return false;}p.waitForFinished(-1);if(stdoutData)*stdoutData=p.readAllStandardOutput();if(stderrData)*stderrData=p.readAllStandardError();if(p.exitStatus()!=QProcess::NormalExit||p.exitCode()!=0){if(error)*error=QString::fromLocal8Bit(stderrData?*stderrData:p.readAllStandardError());return false;}return true;}
static QString probe(const QString&path){QProcess p;p.start("ffprobe",{"-v","error","-show_entries","format=duration","-of","default=nw=1:nk=1",path});if(!p.waitForStarted(2000))return {};p.waitForFinished(5000);return QString::fromLocal8Bit(p.readAllStandardOutput()).trimmed();}
bool FluxMediaEngine::inspectAudio(const QString&path,FluxAudioInfo*info,QString*error){if(!info)return false;info->path=path;info->duration=probe(path).toDouble();if(info->duration<=0&&error)*error="Unable to inspect audio. Ensure FFmpeg/FFprobe is installed.";return info->duration>0;}
bool FluxMediaEngine::inspectVideo(const QString&path,FluxVideoInfo*info,QString*error){if(!info)return false;QProcess p;p.start("ffprobe",{"-v","error","-select_streams","v:0","-show_entries","stream=width,height,r_frame_rate,nb_frames","-show_entries","format=duration","-of","default=noprint_wrappers=1",path});if(!p.waitForStarted(2000)){if(error)*error="FFprobe was not found.";return false;}p.waitForFinished(5000);const QString out=QString::fromLocal8Bit(p.readAllStandardOutput());if(out.isEmpty()){if(error)*error="Unable to inspect video";return false;}auto val=[&](const QString&k){const auto m=QRegularExpression(k+"=(.+)").match(out);return m.hasMatch()?m.captured(1).trimmed():QString();};info->path=path;info->width=val("width").toInt();info->height=val("height").toInt();info->frames=val("nb_frames").toInt();info->duration=val("duration").toDouble();const QString rate=val("r_frame_rate");const auto parts=rate.split('/');if(parts.size()==2&&parts[1].toDouble()>0)info->fps=qRound(parts[0].toDouble()/parts[1].toDouble());info->fps=qBound(1,info->fps,240);return true;}
bool FluxMediaEngine::decodeAudioPcm(const QString&path,QByteArray*out,int sampleRate,int channels,QString*error){QByteArray err;return runFfmpeg({"-v","error","-i",path,"-f","f32le","-ar",QString::number(sampleRate),"-ac",QString::number(channels),"pipe:1"},out,&err,error);}
QVector<float> FluxMediaEngine::buildWaveform(const QString&path,int samples,QString*error){QByteArray pcm;if(!decodeAudioPcm(path,&pcm,48000,1,error))return {};const float*data=reinterpret_cast<const float*>(pcm.constData());const int n=pcm.size()/int(sizeof(float));if(n<=0)return {};samples=qMax(1,samples);QVector<float> result(samples);for(int i=0;i<samples;++i){const int a=int((qint64(i)*n)/samples);const int b=qMax(a+1,int((qint64(i+1)*n)/samples));float peak=0;for(int j=a;j<b&&j<n;++j)peak=qMax(peak,std::abs(data[j]));result[i]=peak;}return result;}
QImage FluxMediaEngine::extractVideoFrame(const QString&path,int frame,int fps,const QSize&size,QString*error){const QString stamp=QString::number(qMax(0,frame)/double(qMax(1,fps)),'f',6);QStringList args={"-v","error","-ss",stamp,"-i",path,"-frames:v","1","-f","image2","pipe:1"};if(size.isValid())args<<"-vf"<<QString("scale=%1:%2").arg(size.width()).arg(size.height());QByteArray out,err;if(!runFfmpeg(args,&out,&err,error))return {};QImage image;image.loadFromData(out,"PNG");if(image.isNull()&&error)*error="Could not decode video frame";return image;}
