#include "fluxtimelinewidget.h"
#include "fluxdocument.h"
#include <QKeyEvent>
#include <QMouseEvent>
#include <QPainter>
#include <algorithm>

FluxTimelineWidget::FluxTimelineWidget(FluxDocument*document,QWidget*parent):QWidget(parent),m_document(document){setFocusPolicy(Qt::StrongFocus);m_animation.setFrameRange(0,qMax(1,document?document->frameCount()-1:119));m_animation.setFps(24);m_animation.addTrack(QStringLiteral("Exposure"),QStringLiteral("Frame"));m_animation.addTrack(QStringLiteral("Opacity"),QStringLiteral("Opacity"));m_animation.addTrack(QStringLiteral("Transform"),QStringLiteral("Transform"));setMinimumHeight(280);}
void FluxTimelineWidget::setCurrentFrame(int frame){m_current=qBound(0,frame,m_document?m_document->frameCount()-1:0);update();}
void FluxTimelineWidget::paintEvent(QPaintEvent*){QPainter p(this);p.fillRect(rect(),QColor("#111318"));p.setPen(QColor("#d7dbe2"));p.drawText(12,20,m_graph?"GRAPH EDITOR":"DOPE SHEET / EXPOSURE");const int frames=qMax(1,m_document?m_document->frameCount():120);const int visible=qMax(1,(width()-m_trackOffset)/m_frameWidth);p.setPen(QColor("#767d89"));for(int f=0;f<qMin(frames,visible);++f)if(f%5==0)p.drawText(m_trackOffset+f*m_frameWidth,40,QString::number(f+1));for(int r=0;r<m_animation.tracks().size();++r){const int y=50+r*m_rowHeight;p.setPen(QColor("#303640"));p.drawLine(m_trackOffset,y+22,width(),y+22);p.setPen(QColor("#d8dce4"));p.drawText(8,y+16,m_animation.tracks()[r].name);for(int x=0;x<frames&&m_trackOffset+x*m_frameWidth<width();++x){QRect cell(m_trackOffset+x*m_frameWidth,y,m_frameWidth,m_rowHeight-6);if(x==m_current)p.fillRect(cell,QColor("#2e3644"));p.setPen(QColor("#262c35"));p.drawRect(cell);}for(const auto&k:m_animation.tracks()[r].keys){QPoint c(m_trackOffset+k.frame*m_frameWidth+m_frameWidth/2,y+10);QPolygon poly;poly<<QPoint(c.x(),c.y()-6)<<QPoint(c.x()+6,c.y())<<QPoint(c.x(),c.y()+6)<<QPoint(c.x()-6,c.y());p.setBrush(k.hold?QColor("#d7b45a"):QColor("#8aa8ff"));p.setPen(Qt::NoPen);p.drawPolygon(poly);}}p.fillRect(m_trackOffset+m_current*m_frameWidth,38,2,height()-38,QColor("#ffffff"));for(const auto&m:m_animation.markers()){const int x=m_trackOffset+m.frame*m_frameWidth;p.setPen(QColor(m.color.isEmpty()?"#8aa8ff":m.color));p.drawLine(x,28,x,height());p.drawText(x+3,32,m.name);}}
void FluxTimelineWidget::mousePressEvent(QMouseEvent*e){if(e->button()==Qt::LeftButton&&e->position().x()>=m_trackOffset){m_current=qBound(0,int((e->position().x()-m_trackOffset)/m_frameWidth),m_document?m_document->frameCount()-1:0);if(m_document)m_document->setFrame(m_current);emit frameChanged(m_current);update();}}
void FluxTimelineWidget::mouseDoubleClickEvent(QMouseEvent*e){if(e->position().x()>=m_trackOffset){m_current=qBound(0,int((e->position().x()-m_trackOffset)/m_frameWidth),m_document?m_document->frameCount()-1:0);addKeyAt(m_current);}}
void FluxTimelineWidget::keyPressEvent(QKeyEvent*e){switch(e->key()){case Qt::Key_Insert:insertFrame();break;case Qt::Key_Delete:deleteFrame();break;case Qt::Key_D:duplicateFrame();break;case Qt::Key_G:m_graph=!m_graph;update();break;case Qt::Key_H:if(!m_animation.tracks().isEmpty())m_animation.addKey(0,m_current,QStringLiteral("Hold"),true,"Hold");update();break;default:QWidget::keyPressEvent(e);}}
void FluxTimelineWidget::addKeyAt(int frame){if(m_animation.tracks().isEmpty())return;m_animation.addKey(0,frame,frame,false,"Bezier");update();emit documentEdited();}
void FluxTimelineWidget::insertFrame(){if(!m_document)return;m_document->setFrameCount(m_document->frameCount()+1);m_animation.insertFrame(m_current);update();emit documentEdited();}
void FluxTimelineWidget::deleteFrame(){if(!m_document||m_document->frameCount()<=1)return;m_document->setFrameCount(m_document->frameCount()-1);m_animation.deleteFrame(m_current);m_current=qMin(m_current,m_document->frameCount()-1);m_document->setFrame(m_current);update();emit frameChanged(m_current);emit documentEdited();}
void FluxTimelineWidget::duplicateFrame(){if(!m_document)return;const int source=m_document->frame();m_document->setFrameCount(m_document->frameCount()+1);const int target=qMin(source+1,m_document->frameCount()-1);for(auto&layer:m_document->layers())if(layer.frames.size()==m_document->frameCount())layer.frames[target]=layer.frames[source];m_animation.duplicateFrame(source);m_document->setFrame(target);m_current=target;update();emit frameChanged(target);emit documentEdited();}
