#include "fluxcompositorwidget.h"
#include <QComboBox>
#include <QDoubleSpinBox>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QLabel>
#include <QListWidget>
#include <QPushButton>
#include <QVBoxLayout>

FluxCompositorWidget::FluxCompositorWidget(QWidget*parent):QWidget(parent){auto*root=new QVBoxLayout(this);auto*title=new QLabel("COMPOSE • NODE GRAPH");title->setObjectName("panelTitle");root->addWidget(title);m_nodes=new QListWidget;root->addWidget(m_nodes,1);auto*bar=new QHBoxLayout;m_type=new QComboBox;m_type->addItems({"COLOR","BLUR","GLOW","TRANSFORM","SHADOW","LEVELS","CURVES","HUE_SATURATION","MASK","ADJUSTMENT","PRECOMP","OUTPUT"});bar->addWidget(m_type,1);auto*add=new QPushButton("+ Node");auto*remove=new QPushButton("Remove");bar->addWidget(add);bar->addWidget(remove);root->addLayout(bar);auto*box=new QGroupBox("Node Parameters");auto*form=new QVBoxLayout(box);m_value1=new QDoubleSpinBox;m_value1->setRange(-1000,1000);m_value1->setValue(0);m_value2=new QDoubleSpinBox;m_value2->setRange(-1000,1000);m_value2->setValue(1);m_value3=new QDoubleSpinBox;m_value3->setRange(-1000,1000);m_value3->setValue(1);form->addWidget(m_value1);form->addWidget(m_value2);form->addWidget(m_value3);root->addWidget(box);m_preview=new QPushButton("Render Preview");root->addWidget(m_preview);connect(add,&QPushButton::clicked,this,&FluxCompositorWidget::addNode);connect(remove,&QPushButton::clicked,this,&FluxCompositorWidget::removeNode);connect(m_nodes,&QListWidget::currentRowChanged,this,[this](int){showNodeParameters();});connect(m_value1,qOverload<double>(&QDoubleSpinBox::valueChanged),this,&FluxCompositorWidget::parameterChanged);connect(m_value2,qOverload<double>(&QDoubleSpinBox::valueChanged),this,&FluxCompositorWidget::parameterChanged);connect(m_value3,qOverload<double>(&QDoubleSpinBox::valueChanged),this,&FluxCompositorWidget::parameterChanged);connect(m_preview,&QPushButton::clicked,this,&FluxCompositorWidget::renderPreview);rebuild();}
void FluxCompositorWidget::rebuild(){m_nodes->clear();for(const auto&n:m_compositor.nodes())m_nodes->addItem(QString("%1  •  %2").arg(n.name,n.type));}
void FluxCompositorWidget::addNode(){const QString type=m_type->currentText();const int id=m_compositor.addNode(type,type.left(1)+type.mid(1).toLower());int previous=-1;const auto nodes=m_compositor.nodes();if(nodes.size()>1)previous=nodes[nodes.size()-2].id;if(previous>=0)m_compositor.connectNodes(previous,id);rebuild();m_nodes->setCurrentRow(m_nodes->count()-1);update();}
void FluxCompositorWidget::removeNode(){const int row=m_nodes->currentRow();if(row<0)return;const auto nodes=m_compositor.nodes();if(row<nodes.size())m_compositor.removeNode(nodes[row].id);rebuild();}
void FluxCompositorWidget::syncSelection(){showNodeParameters();}
void FluxCompositorWidget::showNodeParameters(){const int row=m_nodes->currentRow();if(row<0)return;const auto&n=m_compositor.nodes()[row];if(m_value1)m_value1->setValue(n.params.value("brightness",n.params.value("radius",n.params.value("x",0))).toDouble());if(m_value2)m_value2->setValue(n.params.value("contrast",n.params.value("intensity",n.params.value("rotation",1))).toDouble());if(m_value3)m_value3->setValue(n.params.value("saturation",n.params.value("scaleX",1)).toDouble());}
void FluxCompositorWidget::parameterChanged(){const int row=m_nodes->currentRow();if(row<0)return;auto*n=m_compositor.node(m_compositor.nodes()[row].id);if(!n)return;if(n->type=="COLOR"){n->params["brightness"]=m_value1->value();n->params["contrast"]=m_value2->value();n->params["saturation"]=m_value3->value();}else if(n->type=="BLUR"){n->params["radius"]=m_value1->value();}else if(n->type=="GLOW"){n->params["radius"]=m_value1->value();n->params["intensity"]=m_value2->value();}else if(n->type=="TRANSFORM"){n->params["x"]=m_value1->value();n->params["rotation"]=m_value2->value();n->params["scaleX"]=m_value3->value();}}
void FluxCompositorWidget::renderPreview(){m_preview->setText("Preview graph ready • "+QString::number(m_compositor.nodes().size())+" nodes");}
