#include "fluxstudio_nextwindow.h"
#include "canvaswidget.h"
#include "fluxdocument.h"
#include <QApplication>
#include <QAction>
#include <QActionGroup>
#include <QColorDialog>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFileDialog>
#include <QFormLayout>
#include <QGridLayout>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QMenuBar>
#include <QMessageBox>
#include <QPushButton>
#include <QSlider>
#include <QSpinBox>
#include <QStackedWidget>
#include <QStatusBar>
#include <QToolBar>
#include <QToolButton>
#include <QTimer>
#include <QVBoxLayout>
#include <QDockWidget>
#include <algorithm>
namespace{QLabel* L(const QString&s,const char*r=nullptr,QWidget*p=nullptr){auto*w=new QLabel(s,p);if(r)w->setProperty("role",r);return w;}QPushButton* C(const QString&a,const QString&b,QWidget*p){auto*w=new QPushButton(a+QStringLiteral("\n")+b,p);w->setObjectName("fluxHomeCard");w->setMinimumHeight(104);return w;}}
FluxNextWindow::FluxNextWindow(QWidget*p):QMainWindow(p),m_document(new FluxDocument),m_playTimer(new QTimer(this)){
 resize(1680,1040);setMinimumSize(1200,760);setDockNestingEnabled(true);
 qApp->setStyleSheet("QMainWindow,QDockWidget,QToolBar,QStatusBar,QMenuBar,QMenu{background:#17191d;color:#e9edf2}QPushButton,QToolButton,QComboBox,QSpinBox{background:#22262c;color:#e9edf2;border:1px solid #39404a;border-radius:7px;padding:6px 9px}QListWidget{background:#101216;color:#e9edf2;border:1px solid #303640}QListWidget::item:selected{background:#303944}QDockWidget::title{background:#20242a;padding:8px}QLabel[role=brand]{color:#fff;font-size:24px;font-weight:800}QLabel[role=eyebrow]{color:#929ba6;font-size:11px;font-weight:700;letter-spacing:2px}QLabel[role=headline]{color:#f6f7f8;font-size:36px;font-weight:700}QLabel[role=subhead]{color:#aeb6c0;font-size:14px}QPushButton#fluxHomeCard{text-align:left;padding:18px;background:#1d2127}");
 m_canvas=new FluxCanvas(this);m_canvas->setDocument(m_document);m_stack=new QStackedWidget(this);m_home=new QWidget;m_studio=new QWidget;m_stack->addWidget(m_home);m_stack->addWidget(m_studio);setCentralWidget(m_stack);connect(m_canvas,&FluxCanvas::documentChanged,this,&FluxNextWindow::markDirty);connect(m_canvas,&FluxCanvas::cursorInfoChanged,this,[this](const QString&s){if(m_statusLabel)m_statusLabel->setText(s);});m_playTimer->setInterval(42);connect(m_playTimer,&QTimer::timeout,this,&FluxNextWindow::nextFrame);buildHome();buildStudio();buildMenus();buildTopBar();buildToolRail();buildStatusBar();newProject();showHome();}
FluxNextWindow::~FluxNextWindow()=default;
void FluxNextWindow::buildHome(){auto*r=new QVBoxLayout(m_home);r->setContentsMargins(68,48,68,36);r->setSpacing(18);r->addWidget(L("FLUX","brand"));r->addWidget(L("STUDIO / 1.0 PREVIEW","eyebrow"));r->addWidget(L("Draw. Animate. Finish.","headline"));r->addWidget(L("Professional drawing and 2D animation workspace powered by the existing Flux engine.","subhead"));auto*g=new QGridLayout;auto*n=C("NEW PROJECT","Create a production document.",m_home);auto*o=C("OPEN PROJECT","Load a .flux document.",m_home);auto*c=C("CONTINUE","Enter the studio.",m_home);auto*e=C("EXPORT","Export the current frame.",m_home);g->addWidget(n,0,0,1,2);g->addWidget(o,0,2);g->addWidget(c,1,0);g->addWidget(e,1,1,1,2);r->addLayout(g);r->addStretch();r->addWidget(L("DRAW  →  ANIMATE  →  COMPOSE  →  EXPORT","eyebrow"));connect(n,&QPushButton::clicked,this,[this]{newProject();enterStudio();});connect(o,&QPushButton::clicked,this,&FluxNextWindow::openProject);connect(c,&QPushButton::clicked,this,&FluxNextWindow::enterStudio);connect(e,&QPushButton::clicked,this,&FluxNextWindow::exportProjectImage);}
void FluxNextWindow::buildStudio(){auto*r=new QVBoxLayout(m_studio);r->setContentsMargins(0,0,0,0);auto*h=new QHBoxLayout;h->setContentsMargins(10,6,10,6);m_projectLabel=L("Untitled","eyebrow");h->addWidget(m_projectLabel);h->addStretch();h->addWidget(L("RIGHT-CLICK → QUICK WHEEL","eyebrow"));r->addLayout(h);r->addWidget(m_canvas,1);}
void FluxNextWindow::buildMenus(){auto*f=menuBar()->addMenu("File");f->addAction("New",QKeySequence("Ctrl+N"),this,&FluxNextWindow::newProject);f->addAction("Open",QKeySequence("Ctrl+O"),this,&FluxNextWindow::openProject);f->addAction("Save",QKeySequence::Save,this,&FluxNextWindow::saveProject);f->addAction("Save As",QKeySequence("Ctrl+Shift+S"),this,&FluxNextWindow::saveProjectAs);f->addAction("Export",this,&FluxNextWindow::exportProjectImage);f->addAction("Home",QKeySequence("Ctrl+Shift+H"),this,&FluxNextWindow::showHome);auto*v=menuBar()->addMenu("View");auto*g=v->addAction("Grid");g->setCheckable(true);connect(g,&QAction::toggled,this,&FluxNextWindow::toggleGrid);auto*r=v->addAction("Rulers");r->setCheckable(true);connect(r,&QAction::toggled,this,&FluxNextWindow::toggleRulers);auto*o=v->addAction("Onion Skin");o->setCheckable(true);connect(o,&QAction::toggled,this,&FluxNextWindow::toggleOnion);auto*h=v->addAction("Symmetry H");h->setCheckable(true);connect(h,&QAction::toggled,this,&FluxNextWindow::toggleSymmetryH);auto*z=v->addAction("Symmetry V");z->setCheckable(true);connect(z,&QAction::toggled,this,&FluxNextWindow::toggleSymmetryV);v->addAction("Fit Canvas",this,[this]{m_canvas->fitCanvas();});auto*l=menuBar()->addMenu("Layer");l->addAction("Add Paint Layer",this,&FluxNextWindow::addLayer);l->addAction("Add Group",this,&FluxNextWindow::addGroup);l->addAction("Duplicate",this,&FluxNextWindow::duplicateLayer);l->addAction("Delete",this,&FluxNextWindow::deleteLayer);auto*a=menuBar()->addMenu("Animation");a->addAction("Previous",QKeySequence("Left"),this,&FluxNextWindow::previousFrame);a->addAction("Next",QKeySequence("Right"),this,&FluxNextWindow::nextFrame);a->addAction("Play / Pause",QKeySequence("Space"),this,&FluxNextWindow::togglePlayback);}
void FluxNextWindow::buildTopBar(){auto*b=new QToolBar("Flux",this);b->setMovable(false);addToolBar(b);auto*n=b->addAction("New");connect(n,&QAction::triggered,this,&FluxNextWindow::newProject);auto*o=b->addAction("Open");connect(o,&QAction::triggered,this,&FluxNextWindow::openProject);auto*s=b->addAction("Save");connect(s,&QAction::triggered,this,&FluxNextWindow::saveProject);b->addSeparator();auto*t=new QComboBox(b);t->addItems({"Brush","Pencil","Ink","Eraser","Line","Rectangle","Ellipse","Polygon","Star","Bezier","Gradient","Text","Fill","Color Picker","Transform","Pan","Zoom"});b->addWidget(t);connect(t,&QComboBox::currentTextChanged,this,&FluxNextWindow::setTool);m_brushSlider=new QSlider(Qt::Horizontal,b);m_brushSlider->setRange(1,1000);m_brushSlider->setValue(24);m_brushSlider->setFixedWidth(120);b->addWidget(m_brushSlider);connect(m_brushSlider,&QSlider::valueChanged,this,&FluxNextWindow::setBrushSize);m_brushLabel=L("24 px","eyebrow",b);b->addWidget(m_brushLabel);b->addAction("Color",this,&FluxNextWindow::chooseColor);b->addAction("Play",this,&FluxNextWindow::togglePlayback);}
void FluxNextWindow::buildToolRail(){auto*r=new QToolBar("Tools",this);r->setOrientation(Qt::Vertical);r->setMovable(false);auto*g=new QActionGroup(this);g->setExclusive(true);const QStringList n={"B","P","I","E","L","R","O","T","F"},x={"Brush","Pencil","Ink","Eraser","Line","Rectangle","Ellipse","Transform","Fill"};for(int i=0;i<n.size();++i){auto*a=r->addAction(n[i]);a->setCheckable(true);a->setActionGroup(g);connect(a,&QAction::triggered,this,[this,tool=x[i]]{setTool(tool);});if(i==0)a->setChecked(true);}addToolBar(Qt::LeftToolBarArea,r);}
void FluxNextWindow::buildStatusBar(){m_statusLabel=L("Ready","eyebrow",this);statusBar()->addPermanentWidget(m_statusLabel);}
void FluxNextWindow::newProject(){QDialog d(this);auto*f=new QFormLayout(&d);d.setWindowTitle("New Flux Project");auto*n=new QLineEdit("Untitled",&d);auto*w=new QSpinBox(&d);w->setRange(64,16384);w->setValue(1920);auto*h=new QSpinBox(&d);h->setRange(64,16384);h->setValue(1080);auto*fps=new QSpinBox(&d);fps->setRange(1,240);fps->setValue(24);auto*fr=new QSpinBox(&d);fr->setRange(1,10000);fr->setValue(120);f->addRow("Name",n);f->addRow("Width",w);f->addRow("Height",h);f->addRow("FPS",fps);f->addRow("Frames",fr);auto*bb=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel,&d);f->addRow(bb);connect(bb,&QDialogButtonBox::accepted,&d,&QDialog::accept);connect(bb,&QDialogButtonBox::rejected,&d,&QDialog::reject);if(d.exec()!=QDialog::Accepted)return;m_document->create(n->text(),w->value(),h->value());m_document->setFrameCount(fr->value());m_playTimer->setInterval(qMax(1,1000/fps->value()));m_dirty=false;refreshLayerList();syncDocumentToUi();m_canvas->fitCanvas();updateWindowTitle();}
void FluxNextWindow::openProject(){auto p=QFileDialog::getOpenFileName(this,"Open Flux Project",{},"Flux Projects (*.flux)");if(p.isEmpty())return;QString e;if(!m_document->load(p,&e)){QMessageBox::critical(this,"Open failed",e);return;}m_dirty=false;refreshLayerList();syncDocumentToUi();enterStudio();}
void FluxNextWindow::saveProject(){if(m_document->path().isEmpty()){saveProjectAs();return;}QString e;if(!m_document->save(m_document->path(),&e))QMessageBox::critical(this,"Save failed",e);else{m_dirty=false;updateWindowTitle();}}
void FluxNextWindow::saveProjectAs(){auto p=QFileDialog::getSaveFileName(this,"Save Flux Project","Untitled.flux","Flux Projects (*.flux)");if(p.isEmpty())return;QString e;if(!m_document->save(p,&e))QMessageBox::critical(this,"Save failed",e);else{m_dirty=false;updateWindowTitle();}}
void FluxNextWindow::exportProjectImage(){auto p=QFileDialog::getSaveFileName(this,"Export Image","Flux-Export.png","PNG (*.png);;JPEG (*.jpg *.jpeg);;WebP (*.webp)");if(p.isEmpty())return;QString e;if(!m_document->exportImage(p,&e))QMessageBox::critical(this,"Export failed",e);}
void FluxNextWindow::enterStudio(){m_stack->setCurrentWidget(m_studio);for(auto*d:findChildren<QDockWidget*>())d->show();for(auto*b:findChildren<QToolBar*>())b->show();m_canvas->setFocus();}void FluxNextWindow::showHome(){m_stack->setCurrentWidget(m_home);for(auto*d:findChildren<QDockWidget*>())d->hide();for(auto*b:findChildren<QToolBar*>())b->hide();}
void FluxNextWindow::selectLayer(QListWidgetItem*i){if(i)m_document->setActiveLayer(i->data(Qt::UserRole).toInt());m_canvas->update();}void FluxNextWindow::refreshLayerList(){if(!m_layers)return;m_layers->clear();for(int i=m_document->layers().size()-1;i>=0;--i){auto&l=m_document->layers()[i];auto*it=new QListWidgetItem(l.name,m_layers);it->setData(Qt::UserRole,i);if(i==m_document->activeLayerIndex())it->setSelected(true);}}
void FluxNextWindow::addLayer(){m_document->addLayer(QStringLiteral("Paint Layer %1").arg(m_document->layers().size()+1));refreshLayerList();markDirty();}void FluxNextWindow::addGroup(){m_document->addGroup(QStringLiteral("Group %1").arg(m_document->layers().size()+1));refreshLayerList();markDirty();}void FluxNextWindow::duplicateLayer(){if(!m_document->layers().isEmpty()){m_document->duplicateLayer(m_document->activeLayerIndex());refreshLayerList();markDirty();}}void FluxNextWindow::deleteLayer(){if(m_document->layers().size()>1){m_document->removeLayer(m_document->activeLayerIndex());refreshLayerList();markDirty();}}
void FluxNextWindow::setFrame(int f){f=std::clamp(f,0,m_document->frameCount()-1);m_document->setFrame(f);m_canvas->update();}void FluxNextWindow::previousFrame(){setFrame(m_document->frame()?m_document->frame()-1:m_document->frameCount()-1);}void FluxNextWindow::nextFrame(){setFrame((m_document->frame()+1)%qMax(1,m_document->frameCount()));}void FluxNextWindow::togglePlayback(){m_playing=!m_playing;if(m_playing)m_playTimer->start();else m_playTimer->stop();}void FluxNextWindow::updateZoom(int){m_canvas->fitCanvas();}void FluxNextWindow::setBrushSize(int v){m_canvas->setBrushSize(v);if(m_brushLabel)m_brushLabel->setText(QString::number(v)+" px");}void FluxNextWindow::chooseColor(){auto c=QColorDialog::getColor(m_document->foreground(),this);if(c.isValid()){m_document->setForeground(c);m_canvas->setBrushColor(c);}}void FluxNextWindow::toggleGrid(bool b){m_canvas->setGridEnabled(b);m_canvas->update();}void FluxNextWindow::toggleRulers(bool b){m_canvas->setRulersEnabled(b);m_canvas->update();}void FluxNextWindow::toggleOnion(bool b){m_canvas->toggleOnionSkin(b);m_canvas->update();}void FluxNextWindow::toggleSymmetryH(bool b){m_canvas->setSymmetry(b,m_canvas->symmetryVertical());m_canvas->update();}void FluxNextWindow::toggleSymmetryV(bool b){m_canvas->setSymmetry(m_canvas->symmetryHorizontal(),b);m_canvas->update();}void FluxNextWindow::setTool(const QString&s){m_canvas->setTool(s);}void FluxNextWindow::showAbout(){QMessageBox::about(this,"Flux Studio","Flux Studio 1.0 Preview\nC++20 / Qt 6");}void FluxNextWindow::markDirty(){m_dirty=true;updateWindowTitle();}void FluxNextWindow::syncDocumentToUi(){if(m_projectLabel)m_projectLabel->setText(QStringLiteral("%1   %2 × %3").arg(m_document->name()).arg(m_document->width()).arg(m_document->height()));if(m_frames){m_frames->clear();for(int i=0;i<m_document->frameCount();++i)m_frames->addItem(QString::number(i+1));m_frames->setCurrentRow(m_document->frame());}}void FluxNextWindow::updateWindowTitle(){setWindowTitle(QStringLiteral("%1%2 — Flux Studio 1.0 Preview").arg(m_document->name(),m_dirty?" *":""));}
