#include "fluxanimation.h"
#include <QJsonArray>
#include <QtMath>
#include <algorithm>

void FluxAnimationSystem::setFrameRange(int start,int end){m_start=qMax(0,start);m_end=qMax(m_start,end);}
void FluxAnimationSystem::setFps(int fps){m_fps=qBound(1,fps,240);}
FluxAnimationTrack& FluxAnimationSystem::addTrack(const QString&name,const QString&property){FluxAnimationTrack t;t.id=QStringLiteral("track-%1").arg(m_tracks.size()+1);t.name=name;t.property=property;m_tracks.push_back(t);return m_tracks.last();}
void FluxAnimationSystem::removeTrack(int index){if(index>=0&&index<m_tracks.size())m_tracks.removeAt(index);}
void FluxAnimationSystem::insertFrame(int frame,int count){if(count<=0)return;m_end+=count;for(auto&t:m_tracks)for(auto&k:t.keys)if(k.frame>=frame)k.frame+=count;for(auto&m:m_markers)if(m.frame>=frame)m.frame+=count;for(auto&s:m_shots){if(s.start>=frame)s.start+=count;if(s.end>=frame)s.end+=count;}}
void FluxAnimationSystem::deleteFrame(int frame,int count){if(count<=0||frame>m_end)return;const int last=qMin(m_end,frame+count-1);const int n=last-frame+1;m_end=qMax(m_start,m_end-n);for(auto&t:m_tracks){for(int i=t.keys.size()-1;i>=0;--i){if(t.keys[i].frame>=frame&&t.keys[i].frame<=last)t.keys.removeAt(i);else if(t.keys[i].frame>last)t.keys[i].frame-=n;}}for(auto&m:m_markers){if(m.frame>=frame&&m.frame<=last)m.frame=frame;else if(m.frame>last)m.frame-=n;}}
void FluxAnimationSystem::duplicateFrame(int frame){insertFrame(frame+1);for(auto&t:m_tracks){for(int i=t.keys.size()-1;i>=0;--i)if(t.keys[i].frame==frame){auto k=t.keys[i];k.frame++;t.keys.insert(i+1,k);}}}
void FluxAnimationSystem::addKey(int track,int frame,const QVariant&value,bool hold,const QString&interp){if(track<0||track>=m_tracks.size())return;auto&keys=m_tracks[track].keys;for(auto&k:keys)if(k.frame==frame){k.value=value;k.hold=hold;k.interpolation=interp;return;}FluxKeyframe k;k.frame=qBound(m_start,frame,m_end);k.value=value;k.hold=hold;k.interpolation=interp;keys.push_back(k);std::sort(keys.begin(),keys.end(),[](const auto&a,const auto&b){return a.frame<b.frame;});}
QVariant FluxAnimationSystem::interpolate(const FluxKeyframe&a,const FluxKeyframe&b,int frame)const{if(a.hold||b.frame==a.frame)return a.value;const double t=qBound(0.0,(frame-a.frame)/double(b.frame-a.frame),1.0);if(a.value.canConvert<double>()&&b.value.canConvert<double>()){const double av=a.value.toDouble(),bv=b.value.toDouble();double u=t;if(a.interpolation=="Ease In")u=t*t;else if(a.interpolation=="Ease Out")u=1-(1-t)*(1-t);else if(a.interpolation=="Smooth")u=t*t*(3-2*t);return av+(bv-av)*u;}return t<0.5?a.value:b.value;}
QVariant FluxAnimationSystem::evaluate(int track,int frame)const{if(track<0||track>=m_tracks.size()||m_tracks[track].keys.isEmpty())return {};const auto&k=m_tracks[track].keys;if(frame<=k.first().frame)return k.first().value;if(frame>=k.last().frame)return k.last().value;for(int i=1;i<k.size();++i)if(frame<k[i].frame)return interpolate(k[i-1],k[i],frame);return k.last().value;}
void FluxAnimationSystem::addMarker(int frame,const QString&name,const QString&color){FluxAnimationMarker m{qBound(m_start,frame,m_end),name,color};m_markers.push_back(m);}
FluxScene& FluxAnimationSystem::addScene(const QString&name){FluxScene s;s.id=QStringLiteral("scene-%1").arg(m_scenes.size()+1);s.name=name;m_scenes.push_back(s);return m_scenes.last();}
FluxShot& FluxAnimationSystem::addShot(const QString&name,int start,int end,const QString&sceneId){FluxShot s;s.id=QStringLiteral("shot-%1").arg(m_shots.size()+1);s.name=name;s.start=start;s.end=qMax(start,end);s.scene=sceneId;m_shots.push_back(s);for(auto&sc:m_scenes)if(sc.id==sceneId)sc.shotIds.push_back(s.id);return m_shots.last();}
QJsonObject FluxAnimationSystem::toJson()const{QJsonObject o;o["start"]=m_start;o["end"]=m_end;o["fps"]=m_fps;QJsonArray tracks;for(const auto&t:m_tracks){QJsonObject x;x["id"]=t.id;x["name"]=t.name;x["property"]=t.property;x["muted"]=t.muted;x["locked"]=t.locked;QJsonArray keys;for(const auto&k:t.keys){QJsonObject z;z["frame"]=k.frame;z["value"]=QJsonValue::fromVariant(k.value);z["hold"]=k.hold;z["interpolation"]=k.interpolation;keys.append(z);}x["keys"]=keys;tracks.append(x);}o["tracks"]=tracks;QJsonArray marks;for(const auto&m:m_markers){QJsonObject x;x["frame"]=m.frame;x["name"]=m.name;x["color"]=m.color;marks.append(x);}o["markers"]=marks;return o;}
void FluxAnimationSystem::fromJson(const QJsonObject&o){m_start=o["start"].toInt(0);m_end=o["end"].toInt(119);m_fps=o["fps"].toInt(24);m_tracks.clear();for(const auto&v:o["tracks"].toArray()){auto x=v.toObject();FluxAnimationTrack t;t.id=x["id"].toString();t.name=x["name"].toString();t.property=x["property"].toString();t.muted=x["muted"].toBool();t.locked=x["locked"].toBool();for(const auto&kv:x["keys"].toArray()){auto z=kv.toObject();t.keys.push_back({z["frame"].toInt(),z["value"].toVariant(),z["hold"].toBool(),z["interpolation"].toString("Bezier")});}m_tracks.push_back(t);}m_markers.clear();for(const auto&v:o["markers"].toArray()){auto x=v.toObject();m_markers.push_back({x["frame"].toInt(),x["name"].toString(),x["color"].toString()});}}
