#include "mainwindow.h"
#include "canvaswidget.h"
#include "fluxdocument.h"
#include "brusheditor.h"
#include "fluxbrush.h"
#include "fluxlayertree.h"
#include "fluxtimelinewidget.h"

#include <QAction>
#include <QActionGroup>
#include <QColorDialog>
#include <QComboBox>
#include <QDir>
#include <QDockWidget>
#include <QFileDialog>
#include <QFileInfo>
#include <QFormLayout>
#include <QGroupBox>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QHash>
#include <QIcon>
#include <QLabel>
#include <QMessageBox>
#include <QMenuBar>
#include <QPushButton>
#include <QSettings>
#include <QSignalBlocker>
#include <QStandardPaths>
#include <QTimer>
#include <QToolBar>
#include <QTreeWidget>
#include <QVBoxLayout>
#include <functional>

namespace { QLabel* panelTitle(const QString& t){auto*l=new QLabel(t);l->setObjectName("panelTitle");return l;} }

FluxMainWindow::FluxMainWindow(QWidget* parent):QMainWindow(parent),m_document(new FluxDocument),m_playTimer(new QTimer(this)){
    setWindowTitle("Flux Studio — Untitled");resize(1600,980);setDockNestingEnabled(true);m_document->ensureFrame(0);
    m_canvas=new FluxCanvas(this);m_canvas->setDocument(m_document);setCentralWidget(m_canvas);
    connect(m_canvas,&FluxCanvas::documentChanged,this,&FluxMainWindow::markModified);
    connect(m_canvas,&FluxCanvas::cursorInfoChanged,this,[this](const QString&s){if(m_cursorLabel)m_cursorLabel->setText(s);});
    connect(m_playTimer,&QTimer::timeout,this,[this]{int f=m_document->frame()+1;if(f>=m_document->frameCount())f=m_playing?0:m_document->frameCount()-1;m_document->setFrame(f);m_canvas->update();});
    m_playTimer->setInterval(1000/24);
    buildMenus();buildToolbar();buildDocks();restoreLastSession();
    m_autosavePath=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+QStringLiteral("/recovery.flux");
    QTimer*timer=new QTimer(this);timer->setInterval(30000);connect(timer,&QTimer::timeout,this,&FluxMainWindow::autosave);timer->start();polish();
}
FluxMainWindow::~FluxMainWindow(){autosave();delete m_document;}

void FluxMainWindow::buildMenus(){
    auto*file=menuBar()->addMenu("File");file->addAction("New Project",this,&FluxMainWindow::newProject,QKeySequence("Ctrl+N"));file->addAction("Open…",this,&FluxMainWindow::openProject,QKeySequence::Open);file->addSeparator();file->addAction("Save",this,&FluxMainWindow::saveProject,QKeySequence::Save);file->addAction("Save As…",this,&FluxMainWindow::saveProjectAs,QKeySequence("Ctrl+Shift+S"));file->addSeparator();file->addAction("Export Image…",this,&FluxMainWindow::exportImage);file->addSeparator();file->addAction("Quit",this,&QWidget::close,QKeySequence::Quit);
    auto*edit=menuBar()->addMenu("Edit");edit->addAction("Undo",this,&FluxMainWindow::undo,QKeySequence::Undo);edit->addAction("Redo",this,&FluxMainWindow::redo,QKeySequence::Redo);edit->addSeparator();edit->addAction("Select All",this,&FluxMainWindow::selectAll,QKeySequence("Ctrl+A"));edit->addAction("Deselect",this,&FluxMainWindow::deselect,QKeySequence("Ctrl+Shift+A"));edit->addSeparator();edit->addAction("Brush Editor…",this,&FluxMainWindow::openBrushEditor);
    auto*canvas=menuBar()->addMenu("Canvas");canvas->addAction("Fit Canvas",this,&FluxMainWindow::fitCanvas);canvas->addAction("Mirror Horizontal",this,&FluxMainWindow::mirrorHorizontal);canvas->addAction("Mirror Vertical",this,&FluxMainWindow::mirrorVertical);canvas->addAction("Rotate 90°",this,&FluxMainWindow::rotateCanvas);
    auto*select=menuBar()->addMenu("Select");select->addAction("Rectangle Select",this,[this]{m_canvas->setTool("Rectangle Select");});select->addAction("Lasso Select",this,[this]{m_canvas->setTool("Lasso Select");});select->addAction("Contiguous Select",this,[this]{m_canvas->setTool("Contiguous Select");});select->addAction("Transform",this,[this]{m_canvas->setTool("Transform");});
    auto*anim=menuBar()->addMenu("Animation");anim->addAction("Previous Frame",this,[this]{m_document->setFrame(qMax(0,m_document->frame()-1));m_canvas->update();},QKeySequence("Left"));anim->addAction("Next Frame",this,[this]{m_document->setFrame(qMin(m_document->frameCount()-1,m_document->frame()+1));m_canvas->update();},QKeySequence("Right"));anim->addAction("Duplicate Frame",this,[this]{for(auto&l:m_document->layers())if(l.frames.size()==m_document->frameCount())l.frames.insert(m_document->frame()+1,l.frames[m_document->frame()]);m_document->setFrameCount(m_document->frameCount()+1);m_document->setFrame(qMin(m_document->frame()+1,m_document->frameCount()-1));markModified();m_canvas->update();});anim->addAction("Insert Frame",this,[this]{m_document->setFrameCount(m_document->frameCount()+1);markModified();});anim->addAction("Delete Frame",this,[this]{if(m_document->frameCount()>1)m_document->setFrameCount(m_document->frameCount()-1);markModified();});anim->addAction("Toggle Onion Skin",this,&FluxMainWindow::toggleOnionSkin);
    auto*layer=menuBar()->addMenu("Layer");layer->addAction("Add Paint Layer",this,&FluxMainWindow::addLayer);layer->addAction("Add Group",this,&FluxMainWindow::addGroup);layer->addAction("Add Mask",this,&FluxMainWindow::addMask);layer->addAction("Add Vector Mask",this,[this]{m_document->addMask(m_document->activeLayerIndex(),true);refreshLayers();markModified();m_canvas->update();});layer->addAction("Add Adjustment Layer",this,[this]{m_document->addAdjustment("Adjustment "+QString::number(m_document->layers().size()));refreshLayers();markModified();m_canvas->update();});layer->addSeparator();layer->addAction("Duplicate",this,&FluxMainWindow::duplicateLayer);layer->addAction("Merge Down",this,&FluxMainWindow::mergeDown);layer->addAction("Flatten Visible",this,&FluxMainWindow::flattenVisible);layer->addAction("Delete",this,&FluxMainWindow::removeLayer);layer->addSeparator();layer->addAction("Layer Label Color",this,&FluxMainWindow::setLayerLabelColor);layer->addAction("Toggle Layer Style",this,&FluxMainWindow::setLayerStyle);
    auto*window=menuBar()->addMenu("Window");window->addAction("Brush Editor…",this,&FluxMainWindow::openBrushEditor);window->addAction("Reset Workspace",this,[this]{QSettings("Flux","Flux Studio").clear();statusBar()->showMessage("Workspace reset",2000);});menuBar()->addMenu("Filter");menuBar()->addMenu("Help");
}
void FluxMainWindow::buildToolbar(){auto*tb=addToolBar("Flux Tools");tb->setMovable(false);tb->setIconSize(QSize(21,21));auto*group=new QActionGroup(this);group->setExclusive(true);const QStringList tools={"Brush","Pencil","Ink","Airbrush","Marker","Eraser","Rectangle Select","Lasso Select","Contiguous Select","Transform","Fill","Color Picker","Zoom","Pan"};for(const auto&t:tools){auto*a=tb->addAction(t);a->setCheckable(true);a->setData(t);group->addAction(a);connect(a,&QAction::triggered,this,&FluxMainWindow::setToolFromAction);if(t=="Brush")a->setChecked(true);}tb->addSeparator();auto*color=tb->addAction("Color");connect(color,&QAction::triggered,this,&FluxMainWindow::chooseColor);m_colorSwatch=new QLabel;m_colorSwatch->setFixedSize(24,24);m_colorSwatch->setStyleSheet("background:#111;border:1px solid #444;border-radius:5px");tb->addWidget(m_colorSwatch);tb->addSeparator();tb->addWidget(new QLabel(" Size "));m_brushSlider=new QSlider(Qt::Horizontal);m_brushSlider->setRange(1,1000);m_brushSlider->setValue(24);m_brushSlider->setFixedWidth(160);tb->addWidget(m_brushSlider);connect(m_brushSlider,&QSlider::valueChanged,this,&FluxMainWindow::updateBrushSize);m_brushSizeLabel=new QLabel("24 px");tb->addWidget(m_brushSizeLabel);}
void FluxMainWindow::buildDocks(){auto*layers=new QDockWidget("Layers",this);layers->setObjectName("LayersDock");layers->setWidget(makeLayersPanel());addDockWidget(Qt::RightDockWidgetArea,layers);auto*inspector=new QDockWidget("Inspector",this);inspector->setObjectName("InspectorDock");inspector->setWidget(makeInspectorPanel());tabifyDockWidget(layers,inspector);inspector->raise();auto*timeline=new QDockWidget("Timeline",this);timeline->setObjectName("TimelineDock");timeline->setWidget(makeTimelinePanel());addDockWidget(Qt::BottomDockWidgetArea,timeline);timeline->setMinimumHeight(300);}
void FluxMainWindow::addLayerTreeItem(QTreeWidgetItem*parent,int index){const auto&l=m_document->layers()[index];auto*item=parent?new QTreeWidgetItem(parent):new QTreeWidgetItem(m_layers);QString prefix=l.type==FluxLayerType::Group?"▾ ":l.type==FluxLayerType::Mask?"◐ ":l.type==FluxLayerType::VectorMask?"◇ ":l.type==FluxLayerType::Adjustment?"◈ ":"";item->setText(0,prefix+(l.visible?"● ":"○ ")+l.name);item->setText(1,QString::number(int(l.opacity*100))+"%");item->setData(0,Qt::UserRole,index);item->setCheckState(0,l.visible?Qt::Checked:Qt::Unchecked);item->setToolTip(0,FluxDocument::layerTypeName(l.type));const QImage thumb=(l.frames.size()==m_document->frameCount()&&!l.frames[m_document->frame()].isNull())?l.frames[m_document->frame()]:l.image;if(!thumb.isNull())item->setIcon(0,QIcon(QPixmap::fromImage(thumb.scaled(32,32,Qt::KeepAspectRatio,Qt::SmoothTransformation))));if(l.labelColor.isValid())item->setBackground(0,QBrush(l.labelColor));for(int i=0;i<m_document->layers().size();++i)if(m_document->layers()[i].parentIndex==index)addLayerTreeItem(item,i);}
void FluxMainWindow::refreshLayers(){if(!m_layers)return;m_syncingLayers=true;m_layers->clear();for(int i=0;i<m_document->layers().size();++i)if(m_document->layers()[i].parentIndex<0)addLayerTreeItem(nullptr,i);m_syncingLayers=false;}
QWidget*FluxMainWindow::makeLayersPanel(){auto*root=new QWidget;auto*lay=new QVBoxLayout(root);lay->setContentsMargins(10,10,10,10);lay->addWidget(panelTitle("LAYERS"));auto*tree=new FluxLayerTree;m_layers=tree;m_layers->setHeaderLabels({"Layer","Opacity"});m_layers->setSelectionMode(QAbstractItemView::ExtendedSelection);m_layers->setDragDropMode(QAbstractItemView::InternalMove);m_layers->setDefaultDropAction(Qt::MoveAction);m_layers->setDropIndicatorShown(true);m_layers->setAnimated(true);m_layers->header()->setSectionResizeMode(0,QHeaderView::Stretch);m_layers->header()->setSectionResizeMode(1,QHeaderView::ResizeToContents);lay->addWidget(m_layers,1);connect(m_layers,&QTreeWidget::itemSelectionChanged,this,&FluxMainWindow::layerSelectionChanged);connect(m_layers,&QTreeWidget::itemChanged,this,&FluxMainWindow::layerItemChanged);connect(tree,&FluxLayerTree::hierarchyDropped,this,&FluxMainWindow::syncLayerTreeToDocument);auto*row1=new QHBoxLayout;auto*add=new QPushButton("+ Layer");auto*group=new QPushButton("+ Group");auto*mask=new QPushButton("+ Mask");row1->addWidget(add);row1->addWidget(group);row1->addWidget(mask);connect(add,&QPushButton::clicked,this,&FluxMainWindow::addLayer);connect(group,&QPushButton::clicked,this,&FluxMainWindow::addGroup);connect(mask,&QPushButton::clicked,this,&FluxMainWindow::addMask);lay->addLayout(row1);auto*row2=new QHBoxLayout;auto*dup=new QPushButton("Duplicate");auto*merge=new QPushButton("Merge");auto*del=new QPushButton("Delete");auto*solo=new QPushButton("Solo");solo->setCheckable(true);auto*iso=new QPushButton("Isolate");iso->setCheckable(true);row2->addWidget(dup);row2->addWidget(merge);row2->addWidget(del);row2->addWidget(solo);row2->addWidget(iso);connect(dup,&QPushButton::clicked,this,&FluxMainWindow::duplicateLayer);connect(merge,&QPushButton::clicked,this,&FluxMainWindow::mergeDown);connect(del,&QPushButton::clicked,this,&FluxMainWindow::removeLayer);connect(solo,&QPushButton::toggled,this,&FluxMainWindow::setLayerSolo);connect(iso,&QPushButton::toggled,this,&FluxMainWindow::setLayerIsolate);lay->addLayout(row2);auto*row3=new QHBoxLayout;auto*lock=new QPushButton("Lock");lock->setCheckable(true);auto*clip=new QPushButton("Clip");clip->setCheckable(true);auto*inherit=new QPushButton("Alpha");inherit->setCheckable(true);auto*style=new QPushButton("Style");auto*label=new QPushButton("Label");row3->addWidget(lock);row3->addWidget(clip);row3->addWidget(inherit);row3->addWidget(style);row3->addWidget(label);connect(lock,&QPushButton::toggled,this,&FluxMainWindow::setLayerLocked);connect(clip,&QPushButton::toggled,this,&FluxMainWindow::setLayerClipping);connect(inherit,&QPushButton::toggled,this,&FluxMainWindow::setLayerAlphaInheritance);connect(style,&QPushButton::clicked,this,&FluxMainWindow::setLayerStyle);connect(label,&QPushButton::clicked,this,&FluxMainWindow::setLayerLabelColor);lay->addLayout(row3);return root;}
QWidget*FluxMainWindow::makeInspectorPanel(){auto*root=new QWidget;auto*lay=new QVBoxLayout(root);lay->setContentsMargins(12,12,12,12);lay->addWidget(panelTitle("INSPECTOR"));auto*layerBox=new QGroupBox("Layer Properties");auto*lf=new QFormLayout(layerBox);m_blendMode=new QComboBox;m_blendMode->addItems({"Normal","Multiply","Screen","Overlay","Add","Subtract"});auto*opacity=new QSlider(Qt::Horizontal);opacity->setRange(0,100);opacity->setValue(100);connect(m_blendMode,qOverload<int>(&QComboBox::currentIndexChanged),this,&FluxMainWindow::setLayerBlendMode);connect(opacity,&QSlider::valueChanged,this,&FluxMainWindow::setLayerOpacity);lf->addRow("Blend",m_blendMode);lf->addRow("Opacity",opacity);lay->addWidget(layerBox);auto*brush=new QGroupBox("Brush");auto*f=new QFormLayout(brush);auto*flow=new QSlider(Qt::Horizontal);flow->setRange(0,100);flow->setValue(100);auto*stab=new QSlider(Qt::Horizontal);stab->setRange(0,100);stab->setValue(12);connect(stab,&QSlider::valueChanged,this,[this](int v){m_canvas->setStabilization(v/100.0);});f->addRow("Flow",flow);f->addRow("Stabilizer",stab);lay->addWidget(brush);auto*view=new QGroupBox("Canvas View");auto*vf=new QFormLayout(view);auto*onion=new QPushButton("Onion Skin");onion->setCheckable(true);onion->setChecked(true);connect(onion,&QPushButton::toggled,this,[this](bool v){m_canvas->toggleOnionSkin(v);});auto*grid=new QPushButton("Grid");grid->setCheckable(true);grid->setChecked(true);connect(grid,&QPushButton::toggled,this,[this](bool v){m_canvas->setGridEnabled(v);});auto*rulers=new QPushButton("Rulers");rulers->setCheckable(true);rulers->setChecked(true);connect(rulers,&QPushButton::toggled,this,[this](bool v){m_canvas->setRulersEnabled(v);});auto*perspective=new QPushButton("Perspective");perspective->setCheckable(true);connect(perspective,&QPushButton::toggled,this,[this](bool v){m_canvas->setPerspectiveGuide(v);});vf->addRow(onion,grid);vf->addRow(rulers,perspective);lay->addWidget(view);lay->addStretch();return root;}
QWidget*FluxMainWindow::makeTimelinePanel(){auto*root=new QWidget;auto*lay=new QVBoxLayout(root);auto*head=new QHBoxLayout;head->addWidget(panelTitle("ANIMATION • DOPE SHEET / EXPOSURE"));head->addWidget(new QLabel("FPS"));m_fps=new QSpinBox;m_fps->setRange(1,240);m_fps->setValue(24);head->addWidget(m_fps);head->addStretch();auto*play=new QPushButton("▶ Play");connect(play,&QPushButton::clicked,this,&FluxMainWindow::togglePlayback);head->addWidget(play);lay->addLayout(head);auto*timeline=new FluxTimelineWidget(m_document,root);connect(m_fps,qOverload<int>(&QSpinBox::valueChanged),this,[this](int v){m_playTimer->setInterval(qMax(1,1000/v));});connect(timeline,&FluxTimelineWidget::frameChanged,this,[this](int f){m_document->setFrame(f);m_canvas->update();});connect(timeline,&FluxTimelineWidget::documentEdited,this,[this]{markModified();m_canvas->update();});lay->addWidget(timeline,1);return root;}
void FluxMainWindow::layerSelectionChanged(){if(m_syncingLayers||!m_layers)return;auto*item=m_layers->currentItem();if(!item)return;m_document->setActiveLayer(item->data(0,Qt::UserRole).toInt());const auto&l=m_document->activeLayer();if(m_blendMode){QSignalBlocker b(m_blendMode);m_blendMode->setCurrentText(FluxDocument::blendModeName(l.blendMode));}m_canvas->update();}
void FluxMainWindow::layerItemChanged(QTreeWidgetItem*item,int column){if(m_syncingLayers||!item||column!=0)return;int i=item->data(0,Qt::UserRole).toInt();if(i>=0&&i<m_document->layers().size()){m_document->setLayerVisible(i,item->checkState(0)==Qt::Checked);markModified();m_canvas->update();}}
void FluxMainWindow::syncLayerTreeToDocument(){if(!m_layers||m_syncingLayers)return;QVector<int>order;QVector<int>parents;std::function<void(QTreeWidgetItem*,int)>walk=[&](QTreeWidgetItem*p,int parentNew){int count=p?p->childCount():m_layers->topLevelItemCount();for(int k=0;k<count;++k){auto*item=p?p->child(k):m_layers->topLevelItem(k);int old=item->data(0,Qt::UserRole).toInt();order.push_back(old);parents.push_back(parentNew);walk(item,order.size()-1);}};walk(nullptr,-1);if(order.size()!=m_document->layers().size())return;auto old=m_document->layers();QVector<FluxLayer>reordered;QHash<int,int>map;for(int j=0;j<order.size();++j){map[order[j]]=j;reordered.push_back(old[order[j]]);}for(int j=0;j<reordered.size();++j){reordered[j].parentIndex=parents[j]<0?-1:map.value(order[parents[j]],-1);if(reordered[j].maskTarget>=0)reordered[j].maskTarget=map.value(reordered[j].maskTarget,-1);}int active=m_document->activeLayerIndex();m_document->layers()=reordered;m_document->setActiveLayer(map.value(active,0));markModified();m_canvas->update();}
void FluxMainWindow::addLayer(){int parent=-1;if(m_layers&&m_layers->currentItem()){int i=m_layers->currentItem()->data(0,Qt::UserRole).toInt();if(i>=0&&m_document->layers()[i].type==FluxLayerType::Group)parent=i;}m_document->addLayer("Paint Layer "+QString::number(m_document->layers().size()),FluxLayerType::Paint,parent);refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::addGroup(){int parent=-1;if(m_layers&&m_layers->currentItem()){int i=m_layers->currentItem()->data(0,Qt::UserRole).toInt();if(i>=0&&m_document->layers()[i].type==FluxLayerType::Group)parent=i;}m_document->addGroup("Group "+QString::number(m_document->layers().size()),parent);refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::addMask(){m_document->addMask(m_document->activeLayerIndex(),false);refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::duplicateLayer(){m_document->duplicateLayer(m_document->activeLayerIndex());refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::removeLayer(){m_document->removeLayer(m_document->activeLayerIndex());refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::mergeDown(){m_document->mergeDown(m_document->activeLayerIndex());refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::flattenVisible(){m_document->flattenVisible();refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::setLayerOpacity(int value){if(m_syncingLayers)return;m_document->setLayerOpacity(m_document->activeLayerIndex(),value/100.0);markModified();m_canvas->update();}
void FluxMainWindow::setLayerBlendMode(int index){if(m_syncingLayers||!m_blendMode)return;m_document->setLayerBlendMode(m_document->activeLayerIndex(),FluxDocument::blendModeFromName(m_blendMode->itemText(index)));markModified();m_canvas->update();}
void FluxMainWindow::setLayerLocked(bool enabled){m_document->setLayerLocked(m_document->activeLayerIndex(),enabled);refreshLayers();markModified();}
void FluxMainWindow::setLayerClipping(bool enabled){m_document->setLayerClipping(m_document->activeLayerIndex(),enabled);refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::setLayerAlphaInheritance(bool enabled){m_document->setLayerAlphaInherited(m_document->activeLayerIndex(),enabled);refreshLayers();markModified();m_canvas->update();}
void FluxMainWindow::setLayerSolo(bool enabled){m_document->setSolo(m_document->activeLayerIndex(),enabled);markModified();m_canvas->update();}
void FluxMainWindow::setLayerIsolate(bool enabled){m_document->setIsolate(m_document->activeLayerIndex(),enabled);markModified();m_canvas->update();}
void FluxMainWindow::setLayerLabelColor(){const QColor c=QColorDialog::getColor(m_document->activeLayer().labelColor.isValid()?m_document->activeLayer().labelColor:Qt::white,this,"Layer Label Color");if(c.isValid()){m_document->setLayerLabelColor(m_document->activeLayerIndex(),c);refreshLayers();markModified();}}
void FluxMainWindow::setLayerStyle(){auto s=m_document->activeLayer().style;s.enabled=!s.enabled;if(s.enabled){s.outlineOpacity=.8;s.outlineWidth=2;s.outlineColor=m_document->foreground();}m_document->setLayerStyle(m_document->activeLayerIndex(),s);markModified();m_canvas->update();}
void FluxMainWindow::setFrameFromTimeline(int row){if(row<0)return;m_document->setFrame(row);m_canvas->update();}
void FluxMainWindow::refreshTimeline(){if(m_frames){QSignalBlocker b(m_frames);m_frames->setCurrentRow(m_document->frame());}}
void FluxMainWindow::togglePlayback(){m_playing=!m_playing;if(m_playing)m_playTimer->start();else m_playTimer->stop();}
void FluxMainWindow::updateBrushSize(int value){m_canvas->setBrushSize(value);if(m_brushSizeLabel)m_brushSizeLabel->setText(QString::number(value)+" px");}
void FluxMainWindow::chooseColor(){const QColor c=QColorDialog::getColor(m_document->foreground(),this,"Flux Color");if(c.isValid()){m_document->setForeground(c);m_canvas->setBrushColor(c);if(m_colorSwatch)m_colorSwatch->setStyleSheet(QString("background:%1;border:1px solid #444;border-radius:5px").arg(c.name()));}}
void FluxMainWindow::setToolFromAction(){if(auto*a=qobject_cast<QAction*>(sender()))m_canvas->setTool(a->data().toString());}
void FluxMainWindow::openBrushEditor(){BrushEditorDialog dlg(m_canvas->brushEngine(),this);if(dlg.exec()==QDialog::Accepted){m_canvas->setBrushSize(m_canvas->brushEngine()->preset().size);m_canvas->update();}}
void FluxMainWindow::mirrorHorizontal(){m_mirrorH=!m_mirrorH;m_canvas->setMirrorHorizontal(m_mirrorH);}void FluxMainWindow::mirrorVertical(){m_mirrorV=!m_mirrorV;m_canvas->setMirrorVertical(m_mirrorV);}void FluxMainWindow::rotateCanvas(){m_canvasRotation+=90;if(m_canvasRotation>=360)m_canvasRotation=0;m_canvas->setCanvasRotation(m_canvasRotation);}void FluxMainWindow::fitCanvas(){m_canvas->fitCanvas();}void FluxMainWindow::toggleOnionSkin(){m_canvas->toggleOnionSkin(!m_canvas->onionSkin());}void FluxMainWindow::selectAll(){m_canvas->selectAll();}void FluxMainWindow::deselect(){m_canvas->clearSelection();}void FluxMainWindow::undo(){m_canvas->undo();}void FluxMainWindow::redo(){m_canvas->redo();}
void FluxMainWindow::newProject(){m_document->create("Untitled",1920,1080);m_filePath.clear();m_canvas->setDocument(m_document);refreshLayers();setStatus("New project");}
void FluxMainWindow::openProject(){const QString f=QFileDialog::getOpenFileName(this,"Open Flux Project",{},"Flux Project (*.flux)");if(f.isEmpty())return;QString err;if(!m_document->load(f,&err)){QMessageBox::critical(this,"Flux Studio",err);return;}m_filePath=f;m_canvas->setDocument(m_document);refreshLayers();setWindowTitle("Flux Studio — "+QFileInfo(f).completeBaseName());setStatus("✓ Opened");}
void FluxMainWindow::saveProject(){if(m_filePath.isEmpty()){saveProjectAs();return;}QString err;if(!m_document->save(m_filePath,&err))QMessageBox::critical(this,"Save failed",err);else setStatus("✓ Saved");}
void FluxMainWindow::saveProjectAs(){QString f=QFileDialog::getSaveFileName(this,"Save Flux Project",{},"Flux Project (*.flux)");if(f.isEmpty())return;if(!f.endsWith(".flux",Qt::CaseInsensitive))f+=".flux";m_filePath=f;saveProject();}
void FluxMainWindow::exportImage(){const QString f=QFileDialog::getSaveFileName(this,"Export Image",{},"PNG (*.png);;JPEG (*.jpg *.jpeg);;WebP (*.webp)");if(f.isEmpty())return;QString err;if(!m_document->exportImage(f,&err))QMessageBox::critical(this,"Export failed",err);else setStatus("✓ Exported");}
void FluxMainWindow::autosave(){if(!m_document||m_autosavePath.isEmpty())return;QDir().mkpath(QFileInfo(m_autosavePath).absolutePath());m_document->save(m_autosavePath,nullptr);}
void FluxMainWindow::restoreLastSession(){QSettings s("Flux","Flux Studio");restoreGeometry(s.value("geometry").toByteArray());restoreState(s.value("state").toByteArray());refreshLayers();}
void FluxMainWindow::markModified(){setWindowTitle(QString("Flux Studio — %1*").arg(m_filePath.isEmpty()?QStringLiteral("Untitled"):QFileInfo(m_filePath).completeBaseName()));setStatus("● Unsaved");}
void FluxMainWindow::setStatus(const QString&text){if(m_statusLabel)m_statusLabel->setText(text);else statusBar()->showMessage(text);}
void FluxMainWindow::polish(){setStyleSheet(R"(QMainWindow,QWidget{background:#14161a;color:#e7e9ed;font-family:"Segoe UI";font-size:13px}QMenuBar{background:#191b20;border-bottom:1px solid #2a2d34;padding:4px 8px}QMenuBar::item{padding:7px 10px;border-radius:6px}QMenuBar::item:selected{background:#292e38}QMenu{background:#1c1f25;border:1px solid #353a44;padding:5px}QMenu::item{padding:7px 24px 7px 10px;border-radius:5px}QMenu::item:selected{background:#2b303a}QToolBar{background:#181a1f;border:0;border-bottom:1px solid #2b2e35;spacing:4px;padding:6px}QToolBar QToolButton{min-width:70px;min-height:32px;border:1px solid transparent;border-radius:7px}QToolBar QToolButton:hover{background:#252a33}QToolBar QToolButton:checked{background:#353b47;border-color:#4a5261}QDockWidget{border:1px solid #292d34}QDockWidget::title{background:#1b1e23;padding:9px 12px;border-bottom:1px solid #2b2e35}QTreeWidget,QListWidget{background:#17191e;border:1px solid #2a2e36;border-radius:8px}QTreeWidget::item,QListWidget::item{padding:6px;border-radius:5px}QTreeWidget::item:selected,QListWidget::item:selected{background:#303641}QPushButton{background:#252a33;border:1px solid #363b45;padding:7px 11px;border-radius:7px}QPushButton:hover{background:#303640}QPushButton:checked{background:#39404c;border-color:#5a6270}QSlider::groove:horizontal{height:4px;background:#353a44;border-radius:2px}QSlider::handle:horizontal{width:14px;margin:-5px 0;border-radius:7px;background:#e6e8ec}QSpinBox,QDoubleSpinBox,QComboBox{background:#1e2229;border:1px solid #363b45;border-radius:6px;padding:4px 7px}#panelTitle{font-size:11px;font-weight:700;letter-spacing:1.2px;color:#a4aab5}QStatusBar{background:#17191e;border-top:1px solid #2a2e36})");}
